@host = http://localhost:3010/auth

### 회원가입
POST {{host}}/signup
Content-Type: application/json

{
   "email": "example23@example.com",
   "password": "eXampLe22P@ss",
   "name": "관리자23"
}

### 로그인
POST {{host}}/login
Content-Type: application/json

{
   "email": "example2@example.com",
   "password": "eXampLeP@ss"
}